
default: &default
  adapter: postgresql
  encoding: unicode
  username: satoshy
  password: qwerty
  pool: 5
  host: localhost

development:
  <<: *default
  database: jet_videl_development

test:
  <<: *default
  database: jet_video_test

production:
  <<: *default
  database: jet_video_production
  username: satoshy
  password: <%= ENV['JET_VIDEO_DATABASE_PASSWORD'] %>
